<template>
    <div id='hero-unit'>
        <div id="particles-background"></div>
        <br>
        <div class="d-flex flex-column">
            <div class="row mx-auto">
                <div class="alert alert-info transparent-1 shadow">
                    <h1>
                        Hi There, I am <b>Udip Patel</b>, a Web Developer
                    </h1>
                </div>
            </div>
            <img src="https://via.placeholder.com/170" class="row img-thumbnail rounded-circle mx-auto">
      
            
            <div class="row mx-auto padded-from-top">
                <div class="btn-group btn-group-lg" role="group">
                    <a class="btn btn-light btn-space shadow" href='' target='_blank'>
                        <b><i class='far fa-file-alt'></i> My Resume</b>
                    </a>
                    <a class="btn btn-light shadow" href='' target='_blank'>
                        <b><i class='far fa-envelope'></i> Send me an Email</b>
                    </a>
                </div>
            </div>
        </div>
    </div>
</template>


<script>
    $('document').ready(function(){
        //load particlesJS using autogenerated JSON file
        particlesJS.load('particles-background', '../assets/particles.json', function() { });
    });

</script>